export default Object.freeze({
  LISTING: "Listings",
  LISTING_DETAILS: "ListingDetails",
  MESSAGE_DETAILS: "MessageDetails",
  LISTING_EDIT: "ListingEdit",
  CATEGORY: "Category",
  LOGIN: "LoginScreen",
  MESSAGES: "Сообщения",
  REGISTER: "регистр",
  LISTINGS: "Мой список",
  FILTERLISTINGS: "FilterListings",
  ACCOUNT: "Аккаунт",
  CART: "Корзина",
  PAYMENT: "Choose Payment Method",
  CARDLIST: "Card Lists",
  SHIPPING: "Shipping Address",
  ORDER: "Order Confirmation",
  ADDRESS: "Address Form",
  SHIPPINGADDRESS: "ShippingAddress Form",
  ADDCARD: "Add Card",
  ORDERACCEPTED: "Order Accepted",
  SHOPROFILE: "ShopProfile",
  USERROFILE: "UserProfile",
  SHOPROFILEEDIT: "ShopProfile Form",
  VERIFICATION: "Verification",
  RESETPASSWORD: "Resetpassword",
  CARDVERIFICATION: "CardVerification",
  ORDERLIST: "мои заказы",
  ORDERDETAILS: "OrderDetails",
  STATUS: "StatusScreen",
});
